image: node:latest

concurrent:
  global: 1

stages:
  - build
  - deploy

before_script:
  - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"
  - mkdir -p ~/.ssh
  - eval $(ssh-agent -s)
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

  - apt update
  - apt-get install zip -y
  - apt-get install unzip -y
  
build:
  stage: build
  script:

    - npm i
    - npm run build
    - zip -r sphera_project.zip .
    - ssh-add ~/.ssh/spera_key.pem
    - scp -r sphera_project.zip  ""$HOST_NAME"@"$SSH_HOST":/home/sphera"
  only:
      - main
  tags:
      - name_runner


deploy:
  stage: deploy

  script:
    - ssh-add ~/.ssh/spera_key.pem
    - ssh "$HOST_NAME"@"$SSH_HOST" "mkdir -p /home/sphera/sphera-app"
    - ssh "$HOST_NAME"@"$SSH_HOST" "unzip -o /home/sphera/sphera_project.zip  -d /home/sphera/sphera-app"
    - ssh "$HOST_NAME"@"$SSH_HOST" "rm -rf /home/sphera/sphera_project.zip"
    - ssh "$HOST_NAME"@"$SSH_HOST"  "cd /home/sphera/sphera-app/build && pm2 start ecosystemconfig.js"
  dependencies:
    - build
  only:
      - main
  tags:
      - name_runner




