image: node:latest

stages:
  - build
  - deploy
before_script:
  - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"
  - mkdir -p ~/.ssh
  - eval $(ssh-agent -s)
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
build:
  stage: build
  script:
    - npm i
    - npm run build
  artifacts:
    paths:
      - ./build
deploy:
  stage: deploy
  script:
    - ssh-add <(echo "$PRIVATE_KEY")
    - ssh sphera@158.160.46.141 [ -f ~/.ssh/sphera.pem ] || "echo "$PRIVATE_KEY" > ~/.ssh/spherpa.pem
    - ssh sphera@158.160.46.141 "mkdir -p /path/to/build" #prescribe the path
    - scp -r build/* sphera@158.160.46.141:/path/to/build #prescribe the path
    - ssh sphera@158.160.46.141 "cd /path/to/build && pm2 start app.js --watch --ignore-watch="node_modules"
    - rm -rf ./build  ./node_modules 