name: deploy-CI

on:
    push:
      branches:
        - dev
    workflow_dispatch:
    
jobs:
    deploy_app:
      name: run pull
      runs-on: ubuntu-latest
      
      steps: 
            
      - name: install ssh keys
 
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
 
      - name: connect and pull repo
        run:  |
         ssh bravo@18.116.3.154  "cd /home/bravo/BRAVO/BRAVO_BE && git pull origin dev"
         ssh bravo@18.116.3.154  "cd /home/bravo/BRAVO/ && make start"